version: '3.8'

services:
  app:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - vigilant-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  vigilant-db-data: